<a href="https://colab.research.google.com/github/antonyYG/casos-con-pandas/blob/main/Casos_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [65]:
import pandas as pd
from datetime import datetime

In [66]:
caso1 = pd.read_excel('caso_1_ventas_tienda.xlsx')

In [67]:
caso1

   order_id customer_id   product     category  price  quantity       date
0      1001        C001     Mouse  Electronics   25.5         2 2025-01-10
1      1002        C002  Keyboard  Electronics   45.0         1 2025-01-12
2      1003        C003   T-shirt     Clothing   15.0         3 2025-01-14
3      1004        C001   Monitor  Electronics  120.0         1 2025-02-01
4      1005        C004     Jeans     Clothing   40.0         2 2025-02-05
5      1006        C002     Mouse  Electronics   25.5         1 2025-02-07

In [68]:
caso1['total'] = caso1['price'] * caso1['quantity']
caso1.groupby('category')['total'].sum()

category
Clothing       125.0
Electronics    241.5
Name: total, dtype: float64

In [69]:
caso1.groupby('product')['total'].sum()

product
Jeans        80.0
Keyboard     45.0
Monitor     120.0
Mouse        76.5
T-shirt      45.0
Name: total, dtype: float64

In [70]:
caso1['customer_id'].value_counts().head(2)

customer_id
C001    2
C002    2
Name: count, dtype: int64

In [71]:
caso1.groupby('date')['quantity'].sum().sort_values(ascending=False).head(1)

date
2025-01-14    3
Name: quantity, dtype: int64

In [72]:
caso1['mes'] = caso1['date'].dt.to_period('M')
caso1.groupby('mes')['quantity'].sum()

mes
2025-01    6
2025-02    4
Freq: M, Name: quantity, dtype: int64

In [73]:
caso1.groupby('product')['total'].sum().sort_values(ascending=False).head(1)

product
Monitor    120.0
Name: total, dtype: float64

BLOQUE 2

In [74]:
caso2 = pd.read_excel('caso_2_notas_estudiantes.xlsx', index_col='student_id')
caso2

             name  math  english  science  history
student_id
1             Ana    85       90       70       65
2            Luis    75       80       65       70
3           Pedro    60       65       80       75
4           María    95       85       92       88
5            José    70       72       60       66

In [75]:
caso2['promedioEstudiante'] = caso2[['math','english','science','history']].mean(axis=1)
caso2

             name  math  english  science  history  promedioEstudiante
student_id
1             Ana    85       90       70       65                77.5
2            Luis    75       80       65       70                72.5
3           Pedro    60       65       80       75                70.0
4           María    95       85       92       88                90.0
5            José    70       72       60       66                67.0

In [76]:
caso2.loc[caso2['promedioEstudiante'].idxmax()]

name                  María
math                     95
english                  85
science                  92
history                  88
promedioEstudiante     90.0
Name: 4, dtype: object

In [77]:
caso3 = pd.read_excel('caso_3_empleados_asistencia.xlsx')
caso3

   employee_id      name department  hire_date  absences  salary
0          101    Carlos     Ventas 2022-03-01         2    2000
1          102     Lucía         TI 2021-07-15         0    2500
2          103  Fernando         TI 2023-01-10         1    2400
3          104     Clara       RRHH 2020-12-20         5    2300

In [78]:
caso3.loc[caso3['absences'].idxmax()]

employee_id                    104
name                         Clara
department                    RRHH
hire_date      2020-12-20 00:00:00
absences                         5
salary                        2300
Name: 3, dtype: object

In [79]:
caso3.groupby('department')['salary'].mean()

department
RRHH      2300.0
TI        2450.0
Ventas    2000.0
Name: salary, dtype: float64

In [80]:
caso3.loc[caso3['hire_date'].idxmax()]

employee_id                    103
name                      Fernando
department                      TI
hire_date      2023-01-10 00:00:00
absences                         1
salary                        2400
Name: 2, dtype: object

In [81]:
hoy = pd.to_datetime(datetime.today())
caso3['antiguedad'] = (hoy - caso3['hire_date']).dt.days // 365
caso3

   employee_id      name department  hire_date  absences  salary  antiguedad
0          101    Carlos     Ventas 2022-03-01         2    2000           3
1          102     Lucía         TI 2021-07-15         0    2500           4
2          103  Fernando         TI 2023-01-10         1    2400           2
3          104     Clara       RRHH 2020-12-20         5    2300           4

Caso 4

In [82]:
caso4 = pd.read_excel('caso_4_inventario_productos.xlsx')
caso4

,product_id,product_name,category,stock,reorder_level,price,last_restock
0,201,Laptop,Electrónica,15,10,3200,2025-07-01
1,202,Mouse,Accesorios,150,100,80,2025-06-15
2,203,Teclado,Accesorios,80,50,120,2025-06-30
3,204,Monitor,Electrónica,20,15,950,2025-07-10
4,205,Webcam,Accesorios,60,30,150,2025-07-05
5,206,Tablet,Electrónica,10,5,1200,2025-06-20

In [83]:
caso4[caso4['stock']<caso4['reorder_level']]['product_name']

Series([], Name: product_name, dtype: object)

In [84]:
caso4['total'] = caso4['price'] * caso4['stock']
caso4.groupby('category')['total'].sum()

category
Accesorios     30600
Electrónica    79000
Name: total, dtype: int64

In [85]:
caso4.loc[caso4['price'].idxmax()]

product_id                       201
product_name                  Laptop
category                 Electrónica
stock                             15
reorder_level                     10
price                           3200
last_restock     2025-07-01 00:00:00
total                          48000
Name: 0, dtype: object

In [86]:
hoy = pd.to_datetime(datetime.today())
caso4['antiguedad'] = (hoy - caso4['last_restock']).dt.days
caso4

,product_id,product_name,category,stock,reorder_level,price,last_restock,total,antiguedad
0,201,Laptop,Electrónica,15,10,3200,2025-07-01,48000,36
1,202,Mouse,Accesorios,150,100,80,2025-06-15,12000,52
2,203,Teclado,Accesorios,80,50,120,2025-06-30,9600,37
3,204,Monitor,Electrónica,20,15,950,2025-07-10,19000,27
4,205,Webcam,Accesorios,60,30,150,2025-07-05,9000,32
5,206,Tablet,Electrónica,10,5,1200,2025-06-20,12000,47

In [87]:
caso4.loc[caso4['last_restock'].idxmax()]

product_id                       204
product_name                 Monitor
category                 Electrónica
stock                             20
reorder_level                     15
price                            950
last_restock     2025-07-10 00:00:00
total                          19000
antiguedad                        27
Name: 3, dtype: object

Caso5

In [88]:
caso5= pd.read_excel('caso_5_reservas_hotel.xlsx')
caso5

,reservation_id,customer_name,room_type,check_in,check_out,price_per_night,guests
0,301,Carlos,Simple,2025-08-01,2025-08-05,100,1
1,302,Ana,Doble,2025-08-03,2025-08-06,150,2
2,303,Luis,Suite,2025-08-05,2025-08-10,300,2
3,304,María,Doble,2025-08-07,2025-08-12,150,2
4,305,Pedro,Simple,2025-08-09,2025-08-11,100,1

In [89]:
caso5['dias'] = (caso5['check_out'] - caso5['check_in']).dt.days
caso5

,reservation_id,customer_name,room_type,check_in,check_out,price_per_night,guests,dias
0,301,Carlos,Simple,2025-08-01,2025-08-05,100,1,4
1,302,Ana,Doble,2025-08-03,2025-08-06,150,2,3
2,303,Luis,Suite,2025-08-05,2025-08-10,300,2,5
3,304,María,Doble,2025-08-07,2025-08-12,150,2,5
4,305,Pedro,Simple,2025-08-09,2025-08-11,100,1,2

In [90]:
caso5['total_price'] = caso5['dias'] * caso5['price_per_night']
caso5

,reservation_id,customer_name,room_type,check_in,check_out,price_per_night,guests,dias,total_price
0,301,Carlos,Simple,2025-08-01,2025-08-05,100,1,4,400
1,302,Ana,Doble,2025-08-03,2025-08-06,150,2,3,450
2,303,Luis,Suite,2025-08-05,2025-08-10,300,2,5,1500
3,304,María,Doble,2025-08-07,2025-08-12,150,2,5,750
4,305,Pedro,Simple,2025-08-09,2025-08-11,100,1,2,200

In [91]:
caso5.loc[caso5['total_price'].idxmax()]

reservation_id                     303
customer_name                     Luis
room_type                        Suite
check_in           2025-08-05 00:00:00
check_out          2025-08-10 00:00:00
price_per_night                    300
guests                               2
dias                                 5
total_price                       1500
Name: 2, dtype: object

In [92]:
caso5['room_type'].value_counts().head(1)

room_type
Simple    2
Name: count, dtype: int64

In [95]:
caso5['dias'].mean()

np.float64(3.8)

In [96]:
caso5['customer_name'].count()

np.int64(5)

In [98]:
caso5.groupby('room_type')['total_price'].sum()

room_type
Doble     1200
Simple     600
Suite     1500
Name: total_price, dtype: int64

caso6

In [99]:
caso6 = pd.read_excel('caso_6_ventas_regionales.xlsx')
caso6

  region      month  sales  new_customers
0  Norte 2025-01-01  20000            120
1    Sur 2025-01-01  15000            100
2   Este 2025-01-01  18000            110
3  Oeste 2025-01-01  17000             90
4  Norte 2025-02-01  22000            130
5    Sur 2025-02-01  16000            105
6   Este 2025-02-01  19000            115
7  Oeste 2025-02-01  18000            100

In [100]:
caso6.loc[caso6['sales'].idxmax()]

region                         Norte
month            2025-02-01 00:00:00
sales                          22000
new_customers                    130
Name: 4, dtype: object

In [101]:
caso6.groupby(['region', 'month'])['sales'].sum().groupby('region').mean()

region
Este     18500.0
Norte    21000.0
Oeste    17500.0
Sur      15500.0
Name: sales, dtype: float64

In [103]:
caso6.loc[caso6['sales'].idxmax()]

region                         Norte
month            2025-02-01 00:00:00
sales                          22000
new_customers                    130
Name: 4, dtype: object

In [104]:
caso6.to_excel('prueba_6.xlsx', index=False)